# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - evacuation-app-dev-ea

on:
  push:
    branches:
      - feature/add-docker
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://evacutioncontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2e9ef38f814e4b54a2482d3d2619780b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f13c2a7289844c8786ce9c9322f55510 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: evacutioncontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2e9ef38f814e4b54a2482d3d2619780b }}/evacuationapi:${{ github.sha }}
        context: .
        file: ./Evacuation.API/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'evacuation-app-dev-ea'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_63683d33d24741f4820ad54581c35f03 }}
        images: 'evacutioncontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2e9ef38f814e4b54a2482d3d2619780b }}/evacuationapi:${{ github.sha }}'
